---
title: "Assignment 2: Political Economy"
author: "Erin Yuan"
date: '2023-10-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# import libraries
library(tidyverse)
library(ggplot2)
library(viridis)
library(reshape2)
```

# W

```{r}
# read data
ws = read.csv("NewWmeasure.csv") 

# data wrangling
nearby_countries = c("Austria", "Slovakia", "Ukraine", "Serbia", "Romania", "Croatia", "Slovenia")
ws.clean = ws %>%
  filter(country_name %in% c("Hungary", nearby_countries)) %>%
  select(-ccode) %>%
  mutate(country_name = factor(country_name, levels = c("Austria", "Croatia", "Romania", "Serbia", "Slovakia", "Slovenia", "Ukraine", "Hungary"))) %>%
  filter(year >= 1990)
```

```{r, fig.width = 3, fig.height = 2}
# plot of Ws
ggplot(data = ws.clean, mapping = aes(x = year, y = W4, color = country_name)) +
  geom_line(linewidth = 1) + 
  labs(title = str_wrap("Winning coalition size in Hungary and neighboring countries, 1990-2020", 60),
       x = "Year",
       y = "W", 
       caption = paste0("Source: Smith 2022")) +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, name = "Country")
```

```{r}
# view hungary data only
ws.clean %>%
  filter(country_name == "Hungary")
```

# Corruption Perception Index
```{r}
# read data
cpis = read.csv("estat_sdg_16_50_en.csv") 
countries_abbrev = c("AT", "HR", "RO", "RS", "SK", "SI", "UA", "HU") # 2 letter codes of countries
cpis.clean <- cpis %>%
  filter(geo %in% countries_abbrev) %>%
  select(-DATAFLOW, -LAST.UPDATE, -freq, -OBS_FLAG) %>%
  mutate(geo = factor(geo, levels = c("AT", "HR", "RO", "RS", "SK", "SI", "UA", "HU"))) %>%
  mutate(TIME_PERIOD = as.integer(TIME_PERIOD))
# note: UA is not in data
```

```{r}
# view Hungary
cpis.clean %>%
  filter(geo == "HU")
```

```{r, fig.width = 3, fig.height = 2}
# plot of CPI
ggplot(data = cpis.clean, mapping = aes(x = TIME_PERIOD, y = OBS_VALUE, color = geo)) +
  geom_line(linewidth = 1) + 
  labs(title = str_wrap("Corruption perception index in Hungary and neighboring countries, 2012-2022", 60),
       x = "Year",
       y = "CPI", 
       caption = paste0("Source: Transparency International 2022")) +
  theme_minimal() +
  scale_x_continuous(breaks = c(2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022)) +
  scale_color_viridis(discrete = TRUE, name = "Country", labels = c("Austria", "Croatia", "Romania", "Serbia", "Slovakia", "Slovenia", "Hungary"))
```

# Rule of Law
```{r}
# read data
rol = read.csv("3080f1d4-494a-480c-95e7-0cc9b871c53a_Data.csv")
rol.clean <- rol %>%
  select(-Country.Code, -Series.Name, -Series.Code) %>%
  mutate(Country.Name = factor(Country.Name, levels = c("Austria", "Croatia", "Romania", "Serbia", "Slovak Republic", "Slovenia", "Ukraine", "Hungary")))
colnames(rol.clean)[2:ncol(rol.clean)] = substr(colnames(rol.clean)[2:ncol(rol.clean)], 2, 5) # clean up variable names
rol.clean <- rol.clean %>%
  select(-`2000`)
# melt data for graphing
rol.clean.melted = melt(rol.clean, id.vars = "Country.Name", variable.name = "Year", value.name = "ROL") %>%
  mutate(Year = as.numeric(Year)+2001)
```

```{r}
# rule of law in Hungary only
rol.clean.melted %>%
  filter(Country.Name == "Hungary")
```

```{r, fig.width = 3, fig.height = 2}
# plot of ROL
ggplot(data = rol.clean.melted, mapping = aes(x = Year, y = ROL, color = Country.Name)) +
  geom_line(linewidth = 1) + 
  labs(title = str_wrap("Rule of law estimates in Hungary and neighboring countries, 2000-2022", 60),
       x = "Year",
       y = "Rule of Law Estimate", 
       caption = paste0("Source: World Bank 2022")) +
  theme_minimal() +
  scale_color_viridis(discrete = TRUE, name = "Country") # labels = c("Austria", "Croatia", "Romania", "Serbia", "Slovakia", "Slovenia", "Ukraine", "Hungary"))
```
